-- Schema initial de l'application Gestion Commerciale (PostgreSQL)
-- Genere a partir du modele JPA ; les enums sont stockes en varchar (mapping @Enumerated(STRING)).

create table utilisateurs (
    id            bigint generated by default as identity primary key,
    nom           varchar(255) not null,
    prenom        varchar(255) not null,
    email         varchar(255) not null unique,
    mot_de_passe  varchar(255) not null,
    role          varchar(255),
    actif         boolean not null,
    date_creation timestamp(6) not null
);

create table depots (
    id           bigint generated by default as identity primary key,
    numero       integer not null unique check (numero >= 1 and numero <= 5),
    nom          varchar(255) not null,
    localisation varchar(255)
);

create table categories (
    id          bigint generated by default as identity primary key,
    nom         varchar(255) not null,
    description varchar(255)
);

create table produits (
    id               bigint generated by default as identity primary key,
    reference        varchar(255) not null unique,
    designation      varchar(255) not null,
    description      varchar(255),
    prix_unitaireht  numeric(38,2) not null,
    tauxtva          numeric(38,2) not null,
    unite_mesure     varchar(255),
    categorie_id     bigint references categories
);

create table clients (
    id            bigint generated by default as identity primary key,
    nom           varchar(255) not null,
    prenom        varchar(255),
    email         varchar(255) not null unique,
    telephone     varchar(255),
    adresse       varchar(255),
    siret         varchar(255),
    type_client   varchar(255) not null,
    date_creation timestamp(6) not null,
    commercial_id bigint references utilisateurs
);

create table devis (
    id                   bigint generated by default as identity primary key,
    numero               varchar(255) not null unique,
    date_creation        timestamp(6) not null,
    date_validite        date not null,
    statut               varchar(255) not null,
    montantht            numeric(38,2),
    montantttc           numeric(38,2),
    date_reponse_client  timestamp(6),
    commentaire_client   varchar(255),
    client_id            bigint not null references clients,
    commercial_id        bigint not null references utilisateurs
);

create table lignes_devis (
    id            bigint generated by default as identity primary key,
    devis_id      bigint not null references devis,
    produit_id    bigint not null references produits,
    designation   varchar(255),
    quantite      integer not null,
    prix_unitaire numeric(38,2) not null,
    tauxtva       numeric(38,2),
    remise        numeric(38,2),
    montant_ligne numeric(38,2)
);

create table commandes (
    id            bigint generated by default as identity primary key,
    numero        varchar(255) not null unique,
    date_commande timestamp(6) not null,
    statut        varchar(255) not null,
    montantht     numeric(38,2),
    montantttc    numeric(38,2),
    devis_id      bigint references devis,
    client_id     bigint not null references clients,
    commercial_id bigint not null references utilisateurs
);

create table lignes_commande (
    id            bigint generated by default as identity primary key,
    commande_id   bigint not null references commandes,
    produit_id    bigint not null references produits,
    designation   varchar(255),
    quantite      integer not null,
    prix_unitaire numeric(38,2) not null,
    tauxtva       numeric(38,2),
    remise        numeric(38,2),
    montant_ligne numeric(38,2)
);

create table factures (
    id            bigint generated by default as identity primary key,
    numero        varchar(255) not null unique,
    date_facture  timestamp(6) not null,
    date_echeance date not null,
    statut        varchar(255) not null,
    montantht     numeric(38,2),
    montantttc    numeric(38,2),
    montant_paye  numeric(38,2),
    commande_id   bigint references commandes,
    client_id     bigint not null references clients
);

create table lignes_facture (
    id            bigint generated by default as identity primary key,
    facture_id    bigint not null references factures,
    produit_id    bigint not null references produits,
    designation   varchar(255),
    quantite      integer not null,
    prix_unitaire numeric(38,2) not null,
    tauxtva       numeric(38,2),
    remise        numeric(38,2),
    montant_ligne numeric(38,2)
);

create table paiements (
    id            bigint generated by default as identity primary key,
    facture_id    bigint not null references factures,
    date_paiement timestamp(6) not null,
    montant       numeric(38,2) not null,
    mode_paiement varchar(255) not null,
    reference     varchar(255)
);

create table stock_produits (
    id         bigint generated by default as identity primary key,
    produit_id bigint not null references produits,
    depot_id   bigint not null references depots,
    quantite   integer not null,
    unique (produit_id, depot_id)
);

create table mouvements_stock (
    id             bigint generated by default as identity primary key,
    produit_id     bigint not null references produits,
    depot_id       bigint not null references depots,
    type           varchar(255) not null,
    quantite       integer not null,
    quantite_apres integer not null,
    motif          varchar(255),
    date_mouvement timestamp(6) not null,
    utilisateur_id bigint references utilisateurs
);
