-- Migration V2 : Fournisseur, Marque, refactor Client (JOINED)
-- Projet SOGETHERM - Gestion Commerciale

-- ========================================
-- 1. NOUVELLES TABLES : MARQUES
-- ========================================

create table marques (
    id          bigint generated by default as identity primary key,
    nom         varchar(255) not null unique,
    logo        varchar(255),
    telephone   varchar(255),
    email       varchar(255) unique,
    adresse     varchar(255),
    site_web    varchar(255)
);

create table produits_marques (
    produit_id bigint not null references produits,
    marque_id  bigint not null references marques,
    primary key (produit_id, marque_id)
);

-- ========================================
-- 2. NOUVELLES TABLES : FOURNISSEURS
-- ========================================

create table fournisseurs (
    id                bigint generated by default as identity primary key,
    nom               varchar(255) not null,
    email             varchar(255) unique,
    telephone         varchar(255),
    adresse           varchar(255),
    type_fournisseur  varchar(255) not null,
    date_creation     timestamp(6) not null
);

create table fournisseurs_entreprise (
    fournisseur_id  bigint primary key references fournisseurs on delete cascade,
    raison_sociale  varchar(255) not null,
    siret           varchar(255),
    tva_intra       varchar(255)
);

create table fournisseurs_particulier (
    fournisseur_id bigint primary key references fournisseurs on delete cascade,
    prenom         varchar(255)
);

create table produits_fournisseurs (
    produit_id                bigint not null references produits,
    fournisseur_id            bigint not null references fournisseurs,
    reference_fournisseur     varchar(255),
    est_principal             boolean not null default false,
    primary key (produit_id, fournisseur_id)
);

-- ========================================
-- 3. REFACTOR CLIENT : JOINED
-- ========================================

-- Sauvegarde des donnees existantes
create table clients_backup as select * from clients;

-- Suppression des FK qui referencent clients (sinon DROP CASCADE detruit tout)
alter table lignes_devis drop constraint if exists lignes_devis_devis_id_fkey;
alter table devis drop constraint if exists devis_client_id_fkey;
alter table lignes_commande drop constraint if exists lignes_commande_commande_id_fkey;
alter table commandes drop constraint if exists commandes_client_id_fkey;
alter table lignes_facture drop constraint if exists lignes_facture_facture_id_fkey;
alter table factures drop constraint if exists factures_client_id_fkey;

-- Suppression de l'ancienne table (sans CASCADE pour eviter de tout detruire)
drop table if exists clients cascade;

-- Nouvelle table parente
create table clients (
    id            bigint generated by default as identity primary key,
    nom           varchar(255) not null,
    email         varchar(255) not null unique,
    telephone     varchar(255),
    adresse       varchar(255),
    type_client   varchar(255) not null,
    date_creation timestamp(6) not null,
    commercial_id bigint references utilisateurs
);

-- Sous-table entreprise
create table clients_entreprise (
    client_id       bigint primary key references clients on delete cascade,
    raison_sociale  varchar(255) not null,
    siret           varchar(255),
    tva_intra       varchar(255),
    contact_nom     varchar(255),
    contact_prenom  varchar(255)
);

-- Sous-table particulier
create table clients_particulier (
    client_id       bigint primary key references clients on delete cascade,
    prenom          varchar(255),
    date_naissance  date
);

-- Restauration des donnees (les anciens clients deviennent des particuliers par defaut)
insert into clients (id, nom, email, telephone, adresse, type_client, date_creation, commercial_id)
select id, nom, email, telephone, adresse,
       coalesce(type_client, 'PARTICULIER'),
       date_creation, commercial_id
from clients_backup;

-- Restauration des prenoms dans clients_particulier
insert into clients_particulier (client_id, prenom)
select id, prenom from clients_backup where prenom is not null;

-- Suppression de la table de sauvegarde
drop table clients_backup;

-- Restauration des FK sur devis/commandes/factures
alter table devis add constraint devis_client_id_fkey foreign key (client_id) references clients;
alter table commandes add constraint commandes_client_id_fkey foreign key (client_id) references clients;
alter table factures add constraint factures_client_id_fkey foreign key (client_id) references clients;
alter table lignes_devis add constraint lignes_devis_devis_id_fkey foreign key (devis_id) references devis;
alter table lignes_commande add constraint lignes_commande_commande_id_fkey foreign key (commande_id) references commandes;
alter table lignes_facture add constraint lignes_facture_facture_id_fkey foreign key (facture_id) references factures;

-- ========================================
-- 4. LIEN PRODUIT <-> FOURNISSEUR (simple ManyToMany)
-- ========================================

create table produits_fournisseurs_simple (
    produit_id    bigint not null references produits,
    fournisseur_id bigint not null references fournisseurs,
    primary key (produit_id, fournisseur_id)
);
