-- Le cote achat n'existait pas : le stock apparaissait par saisie manuelle,
-- sans commande, sans reception, sans trace de ce qui avait ete engage aupres
-- du fournisseur. Une commande fournisseur porte a la fois le bon de commande
-- et le suivi jusqu'a l'entree en stock.
create table if not exists commandes_fournisseur (
    id                  bigint generated by default as identity primary key,
    numero              varchar(255)  not null unique,
    statut              varchar(255)  not null,
    fournisseur_id      bigint        not null references fournisseurs,
    depot_reception_id  bigint        not null references depots,
    acheteur_id         bigint        references utilisateurs,
    date_creation       timestamp(6),
    date_commande       date,
    date_arrivee_prevue date,
    date_reception      date,
    -- Bloc import : vide pour un achat local, ou la devise est le dirham.
    devise              varchar(3),
    taux_change         numeric(12, 6),
    incoterm            varchar(255),
    transporteur        varchar(255),
    reference_transport varchar(255),
    port_arrivee        varchar(255),
    montant_devise      numeric(15, 2),
    observations        text
);

create table if not exists lignes_commande_fournisseur (
    id                       bigint generated by default as identity primary key,
    commande_fournisseur_id  bigint        not null references commandes_fournisseur,
    produit_id               bigint        not null references produits,
    reference_fournisseur    varchar(255),
    designation              varchar(255),
    quantite_commandee       numeric(15, 2) not null,
    -- Nulle tant que la marchandise n'est pas arrivee : un ecart avec la
    -- quantite commandee signale une casse ou un manquant.
    quantite_recue           numeric(15, 2),
    prix_unitaire_devise     numeric(15, 2),
    montant_devise           numeric(15, 2)
);

create index if not exists idx_lignes_cf_commande
    on lignes_commande_fournisseur (commande_fournisseur_id);
